name: Connect to AWS role and upload to S3

on:
  push:
    branches: [ main ]

env:
  AWS_REGION : "us-east-2"
  S3_BUCKET_NAME: "lauratyler.dev"

permissions:
  id-token: write
  contents: read

jobs:
  UploadToS3:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      # Verify AWS authentication
      - name: STS GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Retrieve secrets
        id: get_secrets
        run: |
          # Retrieve the second secret as JSON
          CLOUD_CHALLENGE_BUCKET_NAME=$(aws secretsmanager get-secret-value --secret-id CLOUD_CHALLENGE_BUCKET_NAME --query SecretString --output text)
          
          # Set environment variables from the secret
          echo "BUCKET_NAME=$(echo $SECRET_JSON | jq -r '.CLOUD_CHALLENGE_BUCKET_NAME')" >> $GITHUB_ENV

      # Upload files to S3
      - name: Upload files to S3
        run: |
          aws s3 sync . s3://${{ env.CLOUD_CHALLENGE_BUCKET_NAME }} --exclude ".git/*" --delete
